// demo/vdf/vdf.mjs — a Wesolowski VDF (evaluate · prove · verify) on
// top of the hydra-bignum API (ROADMAP A2).
//
// A verifiable delay function forces T *sequential* modular squarings:
//
//     y = x^(2^T)  mod N          (N = p·q of unknown factorization)
//
// Each squaring needs the previous one, so no amount of parallel
// hardware makes it faster — wall-clock time itself becomes provable.
// Wesolowski's construction (eprint 2018/623) makes checking the claim
// cheap: derive a random prime l from (N, x, y, T) by Fiat–Shamir, have
// the prover publish π = x^⌊2^T / l⌋, and accept iff
//
//     π^l · x^(2^T mod l)  ==  y   (mod N)
//
// The verifier does ~2·|l| modular multiplications instead of T.
//
// Deliberate demo simplifications (documented, not hidden):
//   - the prover is naive: it materializes q = ⌊2^T / l⌋ as a T-bit
//     BigInt and computes x^q slice by slice (≈2T multiplications —
//     about twice the evaluation itself; production provers stream q
//     with checkpoints instead);
//   - the challenge prime is 256-bit via hash-then-next_prime;
//   - the modulus is generated by the caller, i.e. the demo page is
//     its own trusted setup — whoever knows φ(N) can shortcut the
//     delay with one 2048-bit reduction.
// Hydra is variable-time by design; a VDF is the natural fit — every
// input here is public.
//
// Dependency-injected: pass the hydra-bignum functions in, so this file
// runs unchanged in the browser demo and the node test suite.
//
//   import { init, powMod, nextPrime, gcd } from 'hydra-bignum';
//   import { createVdf } from './vdf.mjs';
//   await init();
//   const vdf = createVdf({ powMod, nextPrime, gcd });

const CHALLENGE_BITS = 256n;      // |l| — 2λ for the λ=128 demo setting

// WebCrypto in the browser, node:crypto's webcrypto under node <19.
let cryptoPromise = null;
function getCrypto() {
  if (!cryptoPromise) {
    cryptoPromise = globalThis.crypto?.subtle
      ? Promise.resolve(globalThis.crypto)
      : import('node:crypto').then((c) => c.webcrypto);
  }
  return cryptoPromise;
}

function bitLength(v) {           // v >= 0n
  if (v === 0n) return 0;
  const hex = v.toString(16);
  return (hex.length - 1) * 4 + (32 - Math.clz32(parseInt(hex[0], 16)));
}

function bigToBytes(v) {          // minimal big-endian bytes, 0n → []
  let hex = v.toString(16);
  if (hex === '0') return new Uint8Array(0);
  if (hex.length & 1) hex = '0' + hex;
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(2 * i, 2 * i + 2), 16);
  return out;
}

// Unambiguous transcript: utf-8 tag, then each value as a 4-byte
// big-endian length prefix + minimal big-endian bytes.
async function sha256Transcript(tag, ...values) {
  const parts = [new TextEncoder().encode(tag)];
  let total = parts[0].length;
  for (const v of values) {
    const b = typeof v === 'bigint' ? bigToBytes(v) : v;   // bigint | Uint8Array
    const len = new Uint8Array(4);
    new DataView(len.buffer).setUint32(0, b.length);
    parts.push(len, b);
    total += 4 + b.length;
  }
  const msg = new Uint8Array(total);
  let off = 0;
  for (const p of parts) { msg.set(p, off); off += p.length; }
  const { subtle } = await getCrypto();
  const digest = new Uint8Array(await subtle.digest('SHA-256', msg));
  let h = 0n;
  for (const byte of digest) h = (h << 8n) | BigInt(byte);
  return h;                       // 256-bit integer
}

export function createVdf({ powMod, nextPrime, gcd }) {

  // ── setup ──────────────────────────────────────────────────────────
  // N = p·q from fresh randomness; p and q are dropped on the floor —
  // that is the point (and the caveat: the machine that ran this knew
  // them for a moment).
  async function generateModulus(bits) {
    const half = bits >> 1;
    const cryptoObj = await getCrypto();
    const randomPrime = () => {
      const bytes = cryptoObj.getRandomValues(new Uint8Array(half / 8));
      let v = 0n;
      for (const b of bytes) v = (v << 8n) | BigInt(b);
      v |= 1n << BigInt(half - 1);   // exactly `half` bits wide
      return nextPrime(v);
    };
    const p = randomPrime();
    let q = randomPrime();
    while (q === p) q = randomPrime();
    return p * q;
  }

  // x = H(seed) expanded to the width of N, reduced into [2, N),
  // re-hashed on the (astronomically unlikely) gcd(x, N) != 1.
  async function deriveInput(N, seed) {
    const seedBytes = new TextEncoder().encode(String(seed));
    const blocks = Math.ceil((bitLength(N) + 64) / 256);
    for (let ctr = 0n; ; ctr++) {
      let v = 0n;
      for (let i = 0n; i < blocks; i++) {
        v = (v << 256n) | await sha256Transcript('hydra-vdf-input', seedBytes, ctr, i);
      }
      const x = 2n + v % (N - 2n);
      if (gcd(x, N) === 1n) return x;
    }
  }

  // Fiat–Shamir challenge: l = next_prime(H(N, x, y, T) with the top
  // bit pinned), so l is always a fresh ~256-bit prime the prover
  // could not choose.  The verifier recomputes l itself — it is bound
  // to the transcript, never trusted from the proof.
  async function deriveChallenge(N, x, y, T) {
    const h = await sha256Transcript('hydra-vdf-challenge', N, x, y, BigInt(T));
    return nextPrime(h | (1n << (CHALLENGE_BITS - 1n)));
  }

  // ── evaluate: y = x^(2^T) mod N ────────────────────────────────────
  // T sequential squarings, done `chunkBits` at a time so a UI can
  // stay alive: each powMod(y, 2^c, N) call is c squarings inside
  // wasm.  `onProgress(done, total)` is awaited — pass one that yields
  // to the event loop.
  async function evaluate(N, x, T, { chunkBits = 4096, onProgress } = {}) {
    let y = x;
    for (let done = 0; done < T; ) {
      const c = Math.min(chunkBits, T - done);
      y = powMod(y, 1n << BigInt(c), N);
      done += c;
      if (onProgress) await onProgress(done, T);
    }
    return y;
  }

  // ── prove: π = x^⌊2^T / l⌋ mod N ───────────────────────────────────
  // The naive prover: materialize q = ⌊2^T / l⌋ (a T-bit BigInt) and
  // raise x to it MSB-first in `chunkBits`-bit slices:
  //     π ← π^(2^c) · x^(slice)   (mod N)
  // Slices come from q's hex string (O(1) each — repeated BigInt
  // shifts of a multi-megabit q would be quadratic), so chunkBits is
  // rounded to a nibble multiple.  ≈2T multiplications total.
  async function prove(N, x, y, T, { chunkBits = 4096, onProgress } = {}) {
    const l = await deriveChallenge(N, x, y, T);
    const q = (1n << BigInt(T)) / l;
    if (q === 0n) return { l, pi: 1n };            // T < |l|: x^0
    const qHex = q.toString(16);
    const nib = Math.max(1, chunkBits >> 2);       // nibbles per slice
    let pi = null;
    let off = 0;
    while (off < qHex.length) {
      const take = off === 0 ? ((qHex.length - 1) % nib) + 1 : nib;
      const slice = BigInt('0x' + qHex.slice(off, off + take));
      pi = pi === null
        ? powMod(x, slice, N)                      // top slice: leading 1 bit
        : (powMod(pi, 1n << BigInt(4 * take), N) * powMod(x, slice, N)) % N;
      off += take;
      if (onProgress) await onProgress(off * 4, qHex.length * 4);
    }
    return { l, pi };
  }

  // ── verify: π^l · x^(2^T mod l) == y ───────────────────────────────
  // ~2·|l| multiplications, however large T is.  The challenge is
  // recomputed from the transcript; proof.l is display-only.
  async function verify(N, x, y, T, { pi }) {
    if (typeof pi !== 'bigint' || pi < 1n || pi >= N) return false;
    if (x <= 1n || x >= N || y < 1n || y >= N) return false;
    const l = await deriveChallenge(N, x, y, T);
    const r = powMod(2n, BigInt(T), l);            // 2^T mod l, exponent is just T
    return (powMod(pi, l, N) * powMod(x, r, N)) % N === y;
  }

  return { generateModulus, deriveInput, deriveChallenge, evaluate, prove, verify };
}

export { bitLength };
